### ISSUE TITLE
신규 유저 등록 플로우

### ISSUE THREAD

**Issue by JangInHwa** [dimipay/dimipay_app_v2#44]

**Comment by JangInHwa** [comment]
![Image](https://github.com/dimipay/dimipay_app_v2/assets/39157412/7bdee625-4514-4cec-99fe-35711a09ba76)

**Comment by JangInHwa** [comment]
@sspzoa 작업 맡아주실 수 있나요?

**Comment by JangInHwa** [comment]
![Image](https://github.com/dimipay/dimipay_app_v2/assets/39157412/58d41172-6646-41af-a5d9-c08de8761222)
![Image](https://github.com/dimipay/dimipay_app_v2/assets/39157412/3f295588-b555-4e25-9f94-a84fbd86b47c)

**Comment by sspzoa** [comment]
@JangInHwa 넵 진행하겠습니다
